# Generated by Django 3.2.6 on 2021-08-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_dialyincome_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('sort', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('num_of_items', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('profit', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('sort', models.CharField(blank=True, default='', max_length=10000, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True)),
                ('num_of_items', models.DecimalField(blank=True, decimal_places=0, max_digits=100, null=True)),
                ('profit', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
