# Generated by Django 3.2.6 on 2021-08-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0054_books_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='stat',
            name='product_id',
            field=models.CharField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sort',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
