# Generated by Django 3.2.6 on 2021-08-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20210831_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='profit',
            new_name='book_profit',
        ),
        migrations.AddField(
            model_name='profit',
            name='stat_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
