# Generated by Django 3.2.6 on 2021-08-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_auto_20210831_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='product_id',
            field=models.CharField(max_length=1000),
        ),
    ]
