# Generated by Django 3.2.6 on 2021-08-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_stat_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='product_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
