# Generated by Django 3.2.6 on 2021-08-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_auto_20210831_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profit',
            new_name='monthly_profit',
        ),
    ]
