# Generated by Django 3.2.6 on 2021-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_rename_profit_monthly_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_products',
            name='sort',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
