# Generated by Django 3.2.6 on 2021-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_alter_books_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='product_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
