# Generated by Django 3.2.6 on 2021-08-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_alter_stat_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='sort',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
